### ISSUE TITLE
Double free or corruption while running glove code

### ISSUE THREAD

**Issue by RahulKulhari** [stanfordnlp/GloVe#8]
Error message is occuring after shuffle file. During iteration is showing nan values
`iter: 001, cost: 0.186454
iter: 002, cost: 0.152860
iter: 003, cost: 0.131222
iter: 004, cost: 0.116344
iter: 005, cost: 0.106716
iter: 006, cost: -nan
iter: 007, cost: -nan
iter: 008, cost: -nan`
 after that during last glove code it is giving mentioned error

`Error in build/glove: double free or corruption (!prev): 0x00000000006244e0 ***`

**Comment by Russell91** [comment]
Are you getting this issue with the text corpus used in demo.sh or your own corpus?

**Comment by RahulKulhari** [comment]
@Russell91 i am getting this issue with my corpus that is 14 gb and only considering unigrams only.

**Comment by Russell91** [comment]
@RahulKulhari Do you have the ability to run gdb or valgrind and give a stack trace, or even better to provide me a download link to the corpus so that I can try to reproduce? Also, are you running on any nonstandard OS or hardware?

**Comment by RahulKulhari** [comment]
@Russell91 I have sent u an email with the gdb log attached. Please advice further.

**Comment by maurice-g** [comment]
I have experienced the double free or corruption issue as well. In my case it turned out that when having words of length `MAX_STRING_LENGTH` in the vocab.txt file, the `save_params` function causes this error. The problem lies in the `fscanf` call, as it tries to write a string of length `MAX_STRING_LENGTH` to the `word` character array, but as c strings are zero terminated, it actually tries to write `MAX_STRING_LENGTH+1` chars. 

The solution is to change line 138 to 
```c
char *word = malloc(sizeof(char) * MAX_STRING_LENGTH + 1);
```
just as it is done in `vocab_count.c`
The NaNs though must be something different. I encountered NaN values as well, but those were related to a threading issue and in my case it produced NaN from iteration one, so I guess this is not the thing you're looking for.

**Comment by RahulKulhari** [comment]
@maurice-g your solution worked. But i am also looking solution of iteration one also. It is happening during sgd.

**Comment by Russell91** [comment]
@maurice-g @RahulKulhari So I did a run with valgrind on the demo corpus and was not able to produce any warnings due to the improperly sized malloc. In any event, I've created a pull request with the suggested fix: https://github.com/stanfordnlp/GloVe/pull/9. Short of having a repro corpus or doing a full rewrite, there isn't much else I can do for these things. But thank you for the report and the suggested fix!
